# Generated by Django 5.1 on 2024-08-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings_patient', to='patients.patientmodel', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.billingmodel', verbose_name='Invoice'),
        ),
    ]
